version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0"]
    networks:
      - my_network
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://root:root@db:5432/chats_app
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chats_app
    volumes:
      - pg_data:/var/lib/postgresql/data
  sidekiq:
    build: .
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - ".:/app"
    depends_on:
      - redis
    links:
      - redis
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network: